spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=gemma2-9b-it
spring.ai.openai.chat.options.temperature=0.4

spring.ai.model.chat=openai
app.model=Gemma
