# DO NOT USE THIS PROFILE!
# DeepSeek currently doesn't support function calling, so it doesn't work with this app.

spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=deepseek-r1-distill-llama-70b
spring.ai.openai.chat.options.temperature=0.6

spring.ai.model.chat=openai
app.model=DeepSeek
